<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BackgroundPicture</name>
   <tag></tag>
   <elementGuidId>902ea389-1f42-423a-a1b3-56f84940d3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;main-carousel&quot;]/div[1]/div/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main-carousel&quot;]/div[1]/div/img[2]</value>
   </webElementProperties>
</WebElementEntity>
